/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CardData } from "./components/card/card";
export namespace Components {
    interface PaCard {
        /**
          * @prop -- card data prop (passed as JSON string to be parsed)
         */
        "cardData": string;
    }
    interface PaCardList {
    }
    interface PaHeader {
    }
    interface PaModal {
    }
}
declare global {
    interface HTMLPaCardElement extends Components.PaCard, HTMLStencilElement {
    }
    var HTMLPaCardElement: {
        prototype: HTMLPaCardElement;
        new (): HTMLPaCardElement;
    };
    interface HTMLPaCardListElement extends Components.PaCardList, HTMLStencilElement {
    }
    var HTMLPaCardListElement: {
        prototype: HTMLPaCardListElement;
        new (): HTMLPaCardListElement;
    };
    interface HTMLPaHeaderElement extends Components.PaHeader, HTMLStencilElement {
    }
    var HTMLPaHeaderElement: {
        prototype: HTMLPaHeaderElement;
        new (): HTMLPaHeaderElement;
    };
    interface HTMLPaModalElement extends Components.PaModal, HTMLStencilElement {
    }
    var HTMLPaModalElement: {
        prototype: HTMLPaModalElement;
        new (): HTMLPaModalElement;
    };
    interface HTMLElementTagNameMap {
        "pa-card": HTMLPaCardElement;
        "pa-card-list": HTMLPaCardListElement;
        "pa-header": HTMLPaHeaderElement;
        "pa-modal": HTMLPaModalElement;
    }
}
declare namespace LocalJSX {
    interface PaCard {
        /**
          * @prop -- card data prop (passed as JSON string to be parsed)
         */
        "cardData"?: string;
        /**
          * custom event to emit value
          * @returns card object
         */
        "onCardViewSelected"?: (event: CustomEvent<CardData>) => void;
    }
    interface PaCardList {
    }
    interface PaHeader {
    }
    interface PaModal {
    }
    interface IntrinsicElements {
        "pa-card": PaCard;
        "pa-card-list": PaCardList;
        "pa-header": PaHeader;
        "pa-modal": PaModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pa-card": LocalJSX.PaCard & JSXBase.HTMLAttributes<HTMLPaCardElement>;
            "pa-card-list": LocalJSX.PaCardList & JSXBase.HTMLAttributes<HTMLPaCardListElement>;
            "pa-header": LocalJSX.PaHeader & JSXBase.HTMLAttributes<HTMLPaHeaderElement>;
            "pa-modal": LocalJSX.PaModal & JSXBase.HTMLAttributes<HTMLPaModalElement>;
        }
    }
}
